### ISSUE TITLE
Unknown package 'gnome-control-center-3.28.2-1.fc28.x86_64'

### ISSUE THREAD

**Issue by cmurf** [abrt/retrace-server#203] opened 2018-06-02 01:31 UTC
This package is official and installed by default. Not sure why I'm getting this message, but generating stack trace locally isn't practical with this much to download and install.

```
Retrace server is unable to process package 'gnome-control-center-3.28.2-1.fc28.x86_64'.
Is it a part of official 'Fedora 28 (Workstation Edition)' repositories?
Unknown package sent to Retrace server.
Do you want to generate a stack trace locally? (It may download a huge amount of data but reporting can't continue without stack trace). [y/N/f] n
Cannot read conf file '/root/.config/abrt/settings/report-cli.conf': No such file or directory
('analyze_CCpp' exited with 1)
reporting finished with exitcode 1
[chris@f28h ~]$ sudo abrt-cli report /var/spool/abrt/ccpp-2018-06-01-16:35:19.890735-6535
('report_uReport' completed successfully)
Ok to upload core dump? (It may contain sensitive data). If your answer is 'No', a stack trace will be generated locally. (It may download a huge amount of data). [y/N/f/e] n
Analyzing coredump 'coredump'
Coredump references 291 debuginfo files, 214 of them are not installed
Initializing package manager
Setting up repositories
Looking for needed packages in repositories
Can't find packages for 1 debuginfo files
Packages to download: 109
Downloading 464.52Mb, installed size: 1923.38Mb. Continue? [y/N] n
Download cancelled by user
```

**Comment by jfilak** [comment] 2018-06-03 05:40
I apologize for the inconvenience, but this kind of error just happens occasionally. It's root cause is in the race conditions between repository synchronizations. We will have a look at the logs to make sure there is nothing serious.

**Comment by cmurf** [comment] 2018-06-03 14:39
I'm still seeing it today.

**Comment by cmurf** [comment] 2018-06-05 03:50
And now 

Retrace server is unable to process package 'firefox-60.0.1-5.fc28.x86_64'.
Is it a part of official 'Fedora 28 (Workstation Edition)' repositories?
Unknown package sent to Retrace server.
Do you want to generate a stack trace locally? (It may download a huge amount of data but reporting can't continue without stack trace). [y/N/f] 

I'm hitting this more and more often lately...

**Comment by marusak** [comment] 2018-06-05 11:31
Hi,

thank you for the report. You are right, we did not pull these packages. The problem is that we had different url and did not updated it as F28 came from development into stable. I'll update it, pull new packages and let you know.

**Comment by marusak** [comment] 2018-06-07 09:10
I've just tested the firefox package and it works. Closing. If you don't that it works, feel free to reopen.

**Closed by marusak** 2018-06-07 09:10 UTC
