### ISSUE TITLE
faf.Coredump2Packages:No debuginfo found for '0bbc8dc5af1bb987c19840333a2e6f2efe18dde7' (linux-vdso.so.1)

### ISSUE THREAD

**Issue by cmurf** [abrt/retrace-server#243] opened 2019-06-23 19:34 UTC
Should the retrace server be capable of supporting Fedora Rawhide or is it always the case crashes need to be processed locally?

```
# abrt-cli list
id 14bf05ba715b0c460395659ae13eb6cb26718b3f
reason:         malloc(): gnome-session-binary killed by SIGSEGV
time:           Sun 23 Jun 2019 12:52:20 PM MDT
cmdline:        /usr/libexec/gnome-session-binary --autostart /usr/share/gdm/greeter/autostart
package:        gnome-session-3.32.0-1.fc30
uid:            42 (gdm)
count:          1
Directory:      /var/spool/abrt/ccpp-2019-06-23-12:52:20.703556-1172
[root@fmac ~]# abrt-cli report /var/spool/abrt/ccpp-2019-06-23-12:52:20.703556-1172
('report_uReport' completed successfully)
Ok to upload core dump? (It may contain sensitive data). If your answer is 'No', a stack trace will be generated locally. (It may download a huge amount of data). [y/N/f/e] y
Querying server settings
Preparing an archive to upload
Uploading 383.4 KiB
Upload successful
Retrace job started
Analyzing crash data
...........................
Preparing environment for backtrace generation
.........................
Retrace job failed
Retrace failed. Try again later and if the problem persists report this issue please.
    2019-06-23 18:59:48 Analyzing crash data
 2019-06-23 19:06:01 INFO:faf.Coredump2Packages:Executing eu-unstrip
INFO:faf.Coredump2Packages:Mapping build-ids into debuginfo packages
WARNING:faf.Coredump2Packages:No debuginfo found for '0bbc8dc5af1bb987c19840333a2e6f2efe18dde7' (linux-vdso.so.1)
INFO:faf.Coredump2Packages:Getting binary packages from debuginfos

    2019-06-23 19:06:01 Preparing environment for backtrace generation
   2019-06-23 19:11:35 /usr/bin/mock init --resultdir /srv/retrace/tasks/650407304/log --configdir /srv/retrace/tasks/650407304 exitted with 30
=== OUTPUT ===
INFO: mock.py version 1.4.16 starting (python version = 3.6.8)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled HW Info plugin
Mock Version: 1.4.16
INFO: Mock Version: 1.4.16
Start: yum install
ERROR: Command failed: 
 # /usr/bin/yum --installroot /var/lib/mock/650407304/root/ --releasever 7.6 --skip-broken install bash cpio glibc-debuginfo abrt-addon-ccpp shadow-utils findutils gdb rpm
Failed to set locale, defaulting to C

================================================================================
 Package                    Arch   Version                         Repository
                                                                           Size
================================================================================
Installing:
 abrt-addon-ccpp            x86_64 2.12.0-4.fc31                   fedora 125 k
 bash                       x86_64 5.0.7-1.fc31                    fedora 1.6 M
 cpio                       x86_64 2.12-10.fc30                    fedora 247 k
 findutils                  x86_64 1:4.6.0-23.fc31                 fedora 513 k
 gdb                        x86_64 8.3.50.20190610-16.fc31         fedora 134 k
 glibc-debuginfo            x86_64 2.29.9000-28.fc31               fedora  13 M
 rpm                        x86_64 4.14.90-0.git14653.18.fc31      fedora 500 k
 shadow-utils               x86_64 2:4.6-14.fc31                   fedora 1.2 M
Installing for dependencies:
 abrt                       x86_64 2.12.0-4.fc31                   fedora 520 k
 abrt-addon-coredump-helper x86_64 2.12.0-4.fc31                   fedora  31 k
 abrt-dbus                  x86_64 2.12.0-4.fc31                   fedora  81 k
 abrt-libs                  x86_64 2.12.0-4.fc31                   fedora  44 k
 abrt-retrace-client        x86_64 2.12.0-4.fc31                   fedora  48 k
 acl                        x86_64 2.2.53-3.fc30                   fedora  68 k
 alternatives               x86_64 1.11-4.fc31                     fedora  33 k
 audit-libs                 x86_64 3.0-0.9.20190507gitf58ec40.fc31 fedora 110 k
 augeas-libs                x86_64 1.12.0-1.fc31                   fedora 428 k
 basesystem                 noarch 11-7.fc30                       fedora 6.9 k
 boost-regex                x86_64 1.69.0-8.fc31                   fedora 305 k
 brotli                     x86_64 1.0.7-3.fc30                    fedora 311 k
 bzip2-libs                 x86_64 1.0.6-29.fc30                   fedora  37 k
 ca-certificates            noarch 2019.2.32-2.fc31                fedora 394 k
 coreutils                  x86_64 8.31-2.fc31                     fedora 1.2 M
 coreutils-common           x86_64 8.31-2.fc31                     fedora 2.0 M
 cracklib                   x86_64 2.9.6-19.fc30                   fedora  77 k
 crypto-policies            noarch 20190527-1.git0b3add8.fc31      fedora  47 k
 cryptsetup-libs            x86_64 2.2.0-0.2.fc31                  fedora 384 k
 ctags                      x86_64 5.8-25.fc30                     fedora 158 k
 curl-minimal               x86_64 7.65.1-1.fc31                   fedora 120 k
 cyrus-sasl-lib             x86_64 2.1.27-1.fc31                   fedora  99 k
 dbus                       x86_64 1:1.12.16-1.fc31                fedora  11 k
 dbus-broker                x86_64 21-3.fc31                       fedora 171 k
 dbus-common                noarch 1:1.12.16-1.fc31                fedora  18 k
 dbus-libs                  x86_64 1:1.12.16-1.fc31                fedora 155 k
 device-mapper              x86_64 1.02.158-1.fc31                 fedora 149 k
 device-mapper-libs         x86_64 1.02.158-1.fc31                 fedora 181 k
 dmidecode                  x86_64 1:3.2-2.fc30                    fedora  78 k
 dnf-data                   noarch 4.2.5-1.fc31                    fedora  52 k
 elfutils                   x86_64 0.176-3.fc31                    fedora 313 k
 elfutils-default-yama-scope
                            noarch 0.176-3.fc31                    fedora  16 k
 elfutils-libelf            x86_64 0.176-3.fc31                    fedora 180 k
 elfutils-libs              x86_64 0.176-3.fc31                    fedora 286 k
 expat                      x86_64 2.2.6-2.fc30                    fedora  92 k
 fedora-gpg-keys            noarch 31-0.2                          fedora 102 k
 fedora-release             noarch 31-0.7                          fedora  11 k
 fedora-release-common      noarch 31-0.7                          fedora  19 k
 fedora-repos               noarch 31-0.2                          fedora 9.2 k
 fedora-repos-rawhide       noarch 31-0.2                          fedora 8.4 k
 file-libs                  x86_64 5.37-2.fc31                     fedora 565 k
 filesystem                 x86_64 3.12-1.fc31                     fedora 1.1 M
 gawk                       x86_64 4.2.1-6.fc31                    fedora 1.1 M
 gdb-headless               x86_64 8.3.50.20190610-16.fc31         fedora 3.6 M
 gdbm-libs                  x86_64 1:1.18-4.fc30                   fedora  50 k
 glib-networking            x86_64 2.61.1-1.fc31                   fedora 150 k
 glib2                      x86_64 2.61.1-2.fc31                   fedora 2.6 M
 glibc                      x86_64 2.29.9000-28.fc31               fedora 3.7 M
 glibc-common               x86_64 2.29.9000-28.fc31               fedora 526 k
 glibc-debuginfo-common     x86_64 2.29.9000-28.fc31               fedora 9.7 M
 glibc-langpack-zu          x86_64 2.29.9000-28.fc31               fedora 434 k
 gmp                        x86_64 1:6.1.2-10.fc31                 fedora 265 k
 gnupg2                     x86_64 2.2.13-1.fc31                   fedora 2.4 M
 gnutls                     x86_64 3.6.8-1.fc31                    fedora 891 k
 gobject-introspection      x86_64 1.60.1-3.fc31                   fedora 248 k
 gpgme                      x86_64 1.12.0-2.fc31                   fedora 314 k
 grep                       x86_64 3.3-2.fc31                      fedora 246 k
 gsettings-desktop-schemas  x86_64 3.32.0-1.fc30                   fedora 624 k
 gzip                       x86_64 1.9-9.fc31                      fedora 151 k
 ima-evm-utils              x86_64 1.1-5.fc30                      fedora  50 k
 iptables-libs              x86_64 1.8.2-1.fc31                    fedora  54 k
 json-c                     x86_64 0.13.1-4.fc30                   fedora  35 k
 keyutils-libs              x86_64 1.6-2.fc30                      fedora  30 k
 kmod-libs                  x86_64 26-3.fc31                       fedora  59 k
 krb5-libs                  x86_64 1.17-31.fc31                    fedora 734 k
 libacl                     x86_64 2.2.53-3.fc30                   fedora  24 k
 libarchive                 x86_64 3.3.3-7.fc31                    fedora 342 k
 libargon2                  x86_64 20171227-2.fc31                 fedora  28 k
 libassuan                  x86_64 2.5.2-2.fc30                    fedora  76 k
 libattr                    x86_64 2.4.48-6.fc31                   fedora  18 k
 libbabeltrace              x86_64 1.5.6-2.fc30                    fedora 184 k
 libblkid                   x86_64 2.34-1.fc31                     fedora 154 k
 libcap                     x86_64 2.26-5.fc30                     fedora  46 k
 libcap-ng                  x86_64 0.7.9-7.fc31                    fedora  27 k
 libcom_err                 x86_64 1.45.2-1.fc31                   fedora  28 k
 libcomps                   x86_64 0.1.11-1.fc31                   fedora  71 k
 libcurl-minimal            x86_64 7.65.1-1.fc31                   fedora 248 k
 libdb                      x86_64 5.3.28-37.fc30                  fedora 735 k
 libdb-utils                x86_64 5.3.28-37.fc30                  fedora 129 k
 libdnf                     x86_64 0.31.0-5.fc31                   fedora 573 k
 libfdisk                   x86_64 2.34-1.fc31                     fedora 203 k
 libffi                     x86_64 3.1-20.fc31                     fedora  32 k
 libgcc                     x86_64 9.1.1-2.fc31                    fedora  91 k
 libgcrypt                  x86_64 1.8.4-3.fc30                    fedora 435 k
 libgomp                    x86_64 9.1.1-2.fc31                    fedora 224 k
 libgpg-error               x86_64 1.33-2.fc30                     fedora 238 k
 libicu                     x86_64 63.2-2.fc31                     fedora 9.0 M
 libidn2                    x86_64 2.2.0-1.fc31                    fedora  90 k
 libipt                     x86_64 2.0-2.fc30                      fedora  51 k
 libksba                    x86_64 1.3.5-9.fc30                    fedora 124 k
 libmodman                  x86_64 2.0.1-19.fc30                   fedora  32 k
 libmodulemd                x86_64 2.5.0-2.fc31                    fedora 177 k
 libmodulemd1               x86_64 1.8.11-2.fc31                   fedora 179 k
 libmount                   x86_64 2.34-1.fc31                     fedora 177 k
 libnghttp2                 x86_64 1.39.1-1.fc31                   fedora  74 k
 libnsl2                    x86_64 1.2.0-4.20180605git4a062cf.fc30 fedora  54 k
 libpcap                    x86_64 14:1.9.0-3.fc30                 fedora 149 k
 libproxy                   x86_64 0.4.15-13.fc30                  fedora  64 k
 libpsl                     x86_64 0.21.0-1.fc31                   fedora  59 k
 libpwquality               x86_64 1.4.0-12.fc30                   fedora  96 k
 librepo                    x86_64 1.10.2-2.fc31                   fedora  90 k
 libreport                  x86_64 2.10.0-3.fc31                   fedora 494 k
 libreport-filesystem       noarch 2.10.0-3.fc31                   fedora  12 k
 libreport-plugin-systemd-journal
                            x86_64 2.10.0-3.fc31                   fedora  20 k
 libreport-plugin-ureport   x86_64 2.10.0-3.fc31                   fedora  33 k
 libreport-web              x86_64 2.10.0-3.fc31                   fedora  30 k
 libseccomp                 x86_64 2.4.1-0.fc31                    fedora  63 k
 libselinux                 x86_64 2.9-2.fc31                      fedora  84 k
 libsemanage                x86_64 2.9-1.fc31                      fedora 112 k
 libsepol                   x86_64 2.9-1.fc31                      fedora 280 k
 libsigsegv                 x86_64 2.11-7.fc30                     fedora  25 k
 libsmartcols               x86_64 2.34-1.fc31                     fedora 123 k
 libsolv                    x86_64 0.7.5-1.fc31                    fedora 387 k
 libsoup                    x86_64 2.67.2-1.fc31                   fedora 361 k
 libstdc++                  x86_64 9.1.1-2.fc31                    fedora 596 k
 libtar                     x86_64 1.2.20-17.fc30                  fedora  35 k
 libtasn1                   x86_64 4.13-7.fc30                     fedora  67 k
 libtirpc                   x86_64 1.1.4-2.rc2.fc30.1              fedora  97 k
 libunistring               x86_64 0.9.10-5.fc30                   fedora 415 k
 libusbx                    x86_64 1.0.22-3.fc31                   fedora  65 k
 libutempter                x86_64 1.1.6-16.fc30                   fedora  24 k
 libuuid                    x86_64 2.34-1.fc31                     fedora  28 k
 libverto                   x86_64 0.3.0-7.fc30                    fedora  20 k
 libxcrypt                  x86_64 4.4.6-1.fc31                    fedora 122 k
 libxml2                    x86_64 2.9.9-2.fc30                    fedora 651 k
 libyaml                    x86_64 0.2.2-1.fc31                    fedora  57 k
 libzstd                    x86_64 1.4.0-1.fc31                    fedora 260 k
 lua-libs                   x86_64 5.3.5-5.fc30                    fedora 104 k
 lz4                        x86_64 1.8.3-2.fc30                    fedora  96 k
 lz4-libs                   x86_64 1.8.3-2.fc30                    fedora  60 k
 mpfr                       x86_64 3.1.6-4.fc30                    fedora 212 k
 ncurses                    x86_64 6.1-10.20180923.fc30            fedora 360 k
 ncurses-base               noarch 6.1-10.20180923.fc30            fedora  59 k
 ncurses-libs               x86_64 6.1-10.20180923.fc30            fedora 288 k
 nettle                     x86_64 3.4.1rc1-3.fc31                 fedora 299 k
 npth                       x86_64 1.6-2.fc30                      fedora  23 k
 openldap                   x86_64 2.4.47-2.fc31                   fedora 294 k
 openssl-libs               x86_64 1:1.1.1c-3.fc31                 fedora 1.4 M
 p11-kit                    x86_64 0.23.16.1-1.fc31                fedora 267 k
 p11-kit-trust              x86_64 0.23.16.1-1.fc31                fedora 133 k
 pam                        x86_64 1.3.1-17.fc30                   fedora 624 k
 pcre                       x86_64 8.43-2.fc31                     fedora 190 k
 pcre2                      x86_64 10.33-5.fc31                    fedora 252 k
 polkit-libs                x86_64 0.116-1.fc31                    fedora  64 k
 popt                       x86_64 1.16-17.fc30                    fedora  55 k
 publicsuffix-list-dafsa    noarch 20190417-1.fc31                 fedora  54 k
 python-pip-wheel           noarch 19.1.1-1.fc31                   fedora 1.1 M
 python-setuptools-wheel    noarch 41.0.1-1.fc31                   fedora 279 k
 python3                    x86_64 3.7.3-3.fc31                    fedora  38 k
 python3-abrt               x86_64 2.12.0-4.fc31                   fedora  39 k
 python3-augeas             noarch 0.5.0-14.fc30                   fedora  27 k
 python3-dbus               x86_64 1.2.8-5.fc30                    fedora 127 k
 python3-dnf                noarch 4.2.5-1.fc31                    fedora 415 k
 python3-gobject-base       x86_64 3.32.1-2.fc31                   fedora 319 k
 python3-gpg                x86_64 1.12.0-2.fc31                   fedora 236 k
 python3-hawkey             x86_64 0.31.0-5.fc31                   fedora  91 k
 python3-libcomps           x86_64 0.1.11-1.fc31                   fedora  44 k
 python3-libdnf             x86_64 0.31.0-5.fc31                   fedora 666 k
 python3-libreport          x86_64 2.10.0-3.fc31                   fedora  49 k
 python3-libs               x86_64 3.7.3-3.fc31                    fedora 7.9 M
 python3-rpm                x86_64 4.14.90-0.git14653.18.fc31      fedora  90 k
 qrencode-libs              x86_64 3.4.4-8.fc30                    fedora  53 k
 readline                   x86_64 8.0-2.fc30                      fedora 191 k
 rpm-build-libs             x86_64 4.14.90-0.git14653.18.fc31      fedora  96 k
 rpm-libs                   x86_64 4.14.90-0.git14653.18.fc31      fedora 287 k
 rpm-sign-libs              x86_64 4.14.90-0.git14653.18.fc31      fedora  27 k
 satyr                      x86_64 0.27-4.fc31                     fedora 113 k
 sed                        x86_64 4.5-3.fc30                      fedora 285 k
 setup                      noarch 2.13.3-1.fc31                   fedora 149 k
 source-highlight           x86_64 3.1.8-24.fc31                   fedora 649 k
 sqlite-libs                x86_64 3.28.0-1.fc31                   fedora 563 k
 systemd                    x86_64 242-3.git7a6d834.fc31           fedora 3.9 M
 systemd-libs               x86_64 242-3.git7a6d834.fc31           fedora 512 k
 systemd-pam                x86_64 242-3.git7a6d834.fc31           fedora 161 k
 systemd-rpm-macros         noarch 242-3.git7a6d834.fc31           fedora  22 k
 tar                        x86_64 2:1.32-1.fc31                   fedora 863 k
 tzdata                     noarch 2019a-1.fc31                    fedora 425 k
 util-linux                 x86_64 2.34-1.fc31                     fedora 2.6 M
 xmlrpc-c                   x86_64 1.51.0-8.fc30                   fedora 178 k
 xmlrpc-c-client            x86_64 1.51.0-8.fc30                   fedora  28 k
 xz                         x86_64 5.2.4-5.fc30                    fedora 143 k
 xz-libs                    x86_64 5.2.4-5.fc30                    fedora  85 k
 zchunk-libs                x86_64 1.1.2-2.fc31                    fedora  49 k
 zlib                       x86_64 1.2.11-15.fc30                  fedora  89 k

Transaction Summary
================================================================================
Install  8 Packages (+184 Dependent packages)

Total download size: 101 M
Installed size: 500 M
RPM needs to be updated
ERROR You need to update rpm to handle:
rpmlib(RichDependencies) <= 4.12.0-1 is needed by glibc-langpack-zu-2.29.9000-28.fc31.x86_64
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2019-06-23.19-11.UAzs7V.yumtx


   2019-06-23 19:11:37 None

Do you want to generate a stack trace locally? (It may download a huge amount of data but reporting can't continue without stack trace). [y/N/f] 
```

**Comment by xsuchy** [comment] 2020-05-05 14:06
Duplicate of https://github.com/abrt/retrace-server/issues/258

**Closed by xsuchy** 2020-05-05 14:06 UTC
Labels: bug
