### ISSUE TITLE
Retrace failed. Try again later and if the problem persists report this issue please.

### ISSUE THREAD

**Issue by cmurf** [abrt/retrace-server#370] opened 2020-09-24 05:16 UTC
```
$ abrt-cli report -v b41905f
Reporting problem b41905f

uReport has been already sent: '/var/spool/abrt/ccpp-2020-09-23-20:51:17.968907-2524'
Bug for '/var/spool/abrt/ccpp-2020-09-23-20:51:17.968907-2524' not yet filed. Continuing.
no actions matching this problem found for event 'collect_GConf'
no actions matching this problem found for event 'collect_vimrc_system'
no actions matching this problem found for event 'collect_vimrc_user'
Element 'xsession_errors' saved
Ok to upload core dump? (It may contain sensitive data). If your answer is 'No', a stack trace will be generated locally. (It may download a huge amount of data). [y/N/f/e] y
Querying server settings
Preparing an archive to upload
Waiting for tar...
Waiting for xz...
Done...
Uploading 380.2 KiB
Upload successful
Retrace job started
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Analyzing crash data
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Preparing environment for backtrace generation
Retrace job failed
Retrace failed. Try again later and if the problem persists report this issue please.
[2020-09-24 05:11:02] [I] Analyzing crash data

Do you want to generate a stack trace locally? (It may download a huge amount of data but reporting can't continue without stack trace). [y/N/f] 
```

**Comment by xsuchy** [comment] 2020-09-29 13:51
Duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1881984

**Closed by xsuchy** 2020-09-29 13:51 UTC

**Comment by Conan-Kudo** [comment] 2020-10-06 13:24
@xsuchy This is not a duplicate of that issue. This is an issue that the retrace server is missing, so remote retracing doesn't work.
