### ISSUE TITLE
Creating base mock evironment should work without retrace-server's full repos

### ISSUE THREAD

**Issue by mbrysa** [abrt/retrace-server#86] opened 2015-07-22 08:15 UTC
Retrace-server's repos are used for creating the mock base env:
https://github.com/abrt/retrace-server/blob/7ad4b5e282239239269455fd37cb03bb3cc0f2cd/src/lib/retrace_worker.py#L330
https://github.com/abrt/retrace-server/blob/7ad4b5e282239239269455fd37cb03bb3cc0f2cd/src/lib/retrace_worker.py#L510
This prevents the exclusive use of FAF repos when `UseFafPackages` is enabled.

**Comment by marusak** [comment] 2017-05-06 19:32
I don't think this blocks the exclusive use of FAF repos anymore. See https://github.com/abrt/retrace-server/commit/2517c9d60acc8687ce2c550374d8520d630f23cd.
Is there any other reason why this is not wanted?

**Comment by jfilak** [comment] 2017-05-09 06:23
@mbrysa is out of the game until he satisfies his corporate dream :)

The issue is about being able to use packages from FAF. If it is possible now, we can close this issue.

Have you managed to deploy retrace-server using the meta-repositories made of FAF packages in Fedora infrastructure?

**Comment by marusak** [comment] 2017-05-09 06:29
Yes I've managed that. You can test it on https://retrace.fedoraproject.org/. Fedora 26 is not yet available but I am adding it today.

And since this issue is resolved, I am closing this.

**Closed by marusak** 2017-05-09 06:29 UTC
