### ISSUE TITLE
can't process virt-manager

### ISSUE THREAD

**Issue by mozeq** [abrt/retrace-server#67] opened 2013-03-26 14:52 UTC
When I try to retrace crash in virt-manager I get this error from the retrace server:

Querying server settings
Retrace server is unable to process package 'virt-manager-0.9.4-4.fc18.x86_64'.
Is it a part of official Fedora release 18 (Spherical Cow) repositories?
Unknown package sent to Retrace server.

The package is from official fedora repo:
 rpm -qi virt-manager
Name        : virt-manager
Version     : 0.9.4
Release     : 4.fc18
Architecture: noarch
Install Date: Wed 16 Jan 2013 06:55:50 PM CET
Group       : Applications/Emulators
Size        : 1766198
License     : GPLv2+
Signature   : RSA/SHA256, Tue 18 Dec 2012 04:48:13 AM CET, Key ID ff01125cde7f38bd
Source RPM  : virt-manager-0.9.4-4.fc18.src.rpm
Build Date  : Mon 17 Dec 2012 09:03:45 PM CET
Build Host  : buildvm-19.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://virt-manager.org/
Summary     : Virtual Machine Manager
Description :
Virtual Machine Manager provides a graphical tool for administering virtual
machines for KVM, Xen, and QEmu. Start, stop, add or remove virtual devices,
connect to a graphical or serial console, and see resource usage statistics
for existing VMs on local or remote machines. Uses libvirt as the backend
management API.

**Comment by jfilak** [comment] 2016-07-20 09:08
Duplicate of: https://github.com/abrt/retrace-server/issues/122

**Closed by jfilak** 2016-07-20 09:08 UTC
